name: SS2kConfigApp
description: Configures the SmartSpin2k using BLE
version: 1.0.5+12

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <=4.0.0"
  # change this in ci_post_clone.sh as well
  flutter: ">3.20.0 <=3.22.3"

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.33.1
  #dynamic_color: ^1.6.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.9
  shared_preferences: ^2.2.0
  #flutter_ota: ^0.1.4
  wakelock_plus: ^1.2.8
  http: ^1.2.0
  font_awesome_flutter: ^10.7.0
  json_theme: ^6.5.3+5
  fl_chart: ^0.68.0
  flutter_archive: ^6.0.3
  path_provider: ^2.1.5
  xml: ^6.5.0
  file_picker: ^8.1.4
  audioplayers: ^6.1.0
  just_audio: ^0.9.36
  share_plus: ^10.1.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/appainter_theme.json
    - assets/sounds/
